#!/bin/bash

export AWS_ACCESS_KEY_ID=[YOUR ACCESS KEY ID]
export AWS_SECRET_ACCESS_KEY=[YOUR SECRET ACCESS KEY]
export S3_BUCKET=[YOUR S3 BUCKET NAME]
export SQS_QUEUE_URL=[YOUR SQS QUEUE URL]
export HOSTNAME=[YOUR HOSTNAME]
